### ISSUE TITLE
ToDo List Proposal

### ISSUE THREAD

**Issue by itisacloud** [itisacloud/IDSTA22-Team-Heigit#1]
- [ ] Write motivation (0.5 Pages)
- [ ] Research Papers State of the art maybe 3-4?
- [ ] Write State of the art (1-2 Pages)
- [ ] Write Project Description (1-2 Pages)
